### ISSUE TITLE
Regression in versions 3.4.1 & 3.4.2; bugs introduced.

### ISSUE THREAD

**Issue by Git-Forked** [Kunzisoft/KeePassDX#1310]
**Describe the bug**
Auto fill is no longer working. Prior to the versions 3.4.1 & 3.4.2 it was working as expected.

**To Reproduce**

1. Go to a website with saved credentials in KeePassDX
2. Click on keyboard change icon
3. Select Magikeyboard
4. Enter database password
5. Select database entry
6. Back at the website select the icons on Magikeyboard to auto fill username and password.

**Expected behavior**

I would expect the auto fill to work just as it used to, however selecting the database entry is not providing the Magikeyboard with the auto fill data.  As well, possibly a second and different bug altogether:  After entering database password, KeePassDX takes me to "Current group" instead of the main database view. 

**KeePass Database**

 - Created with: Android, with a KeePassDX prior to version 3.4.0
 - Location: local
 - Contains attachment: No

**KeePassDX:**

 - Version: 3.4.1 & 3.4.2
 - Build: F-droid
 - Language: English

**Android:**

 - Device: Samsung Galaxy A01
 - Version: 10

**Additional context**

 - Browser for Autofill: Ungoogled Chromium Extensions

**Comment by J-Jamet** [comment]
Duplicate #1309 https://github.com/Kunzisoft/KeePassDX/issues/1304 https://github.com/Kunzisoft/KeePassDX/issues/1299#issuecomment-1100745997

**Comment by JiveMahoney** [comment]
I don't think this is a dup issue. I'm having the same problem. Have to use 3.4.0 for magickeyboard to work correctly.

I don't want to use search, but after 3.4.0, unlocking a database via magickeyboard forces a search. Mine is actually filling the search field with the app name identifier.

For example, unlocking a database using magickey in bromite browser forces a search for org.bromite.bromite. I then have to clear the search, and select the correct entry, which opens the entry instead of populating the magickey, even though I have the latter option enabled.

So pretty much useless, please fix whatever got broke after 3.4.0.

**Comment by J-Jamet** [comment]
@JiveMahoney You haven't read the wiki at all... 
Long press the key button on the Magikeyboard and your issue is fixed, no search.
Else share from your browser to the magikeyboard.

**Comment by J-Jamet** [comment]
> So pretty much useless, please fix whatever got broke after 3.4.0.

You find it useless to fill the keyboard without even making a selection when you are on an application and not a browser?

On the other hand what I find useless is to waste time taking screenshots and writing an explanatory doc for users who don't bother to read and understand why it is possible to search for a package name.

I also don't like to waste my time explaining things again because a user does not like to search in general.

A new feature may be useless for you but not for everyone.

**Comment by JiveMahoney** [comment]
Jeeze, lighten up a bit bud.

I read the wiki years ago when I first started using it.

I don't use apps that I have to log into, I use a browser for everything mostly.

It should be a long press for the new functionality, but whatever. Seemed like a bug to me. Although, I still don't get the share function. I tried it but did it wrong and it ended up replacing my email pass in my database.

Working good now. Thanks.
