### ISSUE TITLE
Out of memory on trying to open database saved by keepassxc

### ISSUE THREAD

**Issue by wheybags** [Kunzisoft/KeePassDX#256]
Hi,
I'm getting an oom when I try to open my database saved by KeepassXC, no matter what database settings I use. I have seen https://github.com/Kunzisoft/KeePassDX/issues/154 but I think some better workaround should be found, as the number of dbs that fail to open will only increase with time.
If I create a db with default settings in the latest version of keepassxc (2.4.1 at time of writing), it loads fine, but when I import all my old data into it, it stops working.
If I open the db and resave it with original Keepass2 version 2.41 and set encryption algo to AES/Rijndael and derivation function to AES-KDF, then it works, but If I open and re-save in keepassxc it breaks again.
I gather the issue is that KeepassDX tries to allocate a block of memory in one go that is too large so some android system heuristics kick in and deny it?
Is there any way to diable this on a per-app basis, or maybe chunk it into a series of smaller allocations?

**Comment by ladidadida** [comment]
I am facing the same issue since I added exactly one more password. 

Do you need any log-data? Unfortunately I have not found out how to create/collect log data.

**Comment by lgrahl** [comment]
Same here. Happy to help as well.

**Comment by J-Jamet** [comment]
Can you upload a database that causes the problem but works with KeePass 2 and KeePassXC? It will allow me to see more easily where the problem is coming from.

**Comment by lgrahl** [comment]
I have to kindly refuse that and hope you understand. Even encrypted, I don't want to hand out this database. I'm no stranger to Android development if that helps.

**Comment by J-Jamet** [comment]
It is obvious that I do not specifically require your database with sensitive data but any database that has the problem to debug it.

**Comment by lgrahl** [comment]
I'd certainly do that if I had another database with that problem. :slightly_smiling_face:

Anyway, I made a quick build and here's the stack trace:

```
E/com.kunzisoft.keepass.database.action.LoadDatabaseRunnable: No memory to load your entire database.
    java.lang.OutOfMemoryError: Failed to allocate a 1750217576 byte allocation with 3427143 free bytes and 188MB until OOM, max allowed footprint 6854287, growth limit 201326592
        at com.kunzisoft.keepass.stream.LEDataInputStream.readBytes(LEDataInputStream.java:108)
        at com.kunzisoft.keepass.database.load.ImporterV4.ReadInnerHeader(ImporterV4.java:228)
        at com.kunzisoft.keepass.database.load.ImporterV4.LoadInnerHeader(ImporterV4.java:211)
        at com.kunzisoft.keepass.database.load.ImporterV4.openDatabase(ImporterV4.java:183)
        at com.kunzisoft.keepass.database.load.ImporterV4.openDatabase(ImporterV4.java:77)
        at com.kunzisoft.keepass.database.Database.loadData(Database.java:161)
        at com.kunzisoft.keepass.database.Database.passUrisAsInputStreams(Database.java:139)
        at com.kunzisoft.keepass.database.Database.loadData(Database.java:121)
        at com.kunzisoft.keepass.database.Database.loadData(Database.java:110)
        at com.kunzisoft.keepass.database.action.LoadDatabaseRunnable.run(LoadDatabaseRunnable.java:71)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by ladidadida** [comment]
I tried to create a new database with enough entries to get the same behavior, but it is not that easy. My orginal faulty db is 28kB of size, the new one I created for testing is now 40KB. But the new one, also created with KeepassXC can now be loaded by KeepassDX without any problem. 

I have pasted my new keepass-db together with keefile in one zip file. The password is 'abc123!!'

@
[keepassfiles.zip](https://github.com/Kunzisoft/KeePassDX/files/3502871/keepassfiles.zip)

**Comment by theScrabi** [comment]
Youp happens to me to now. Just one more key and im out of memory :)

**Comment by lgrahl** [comment]
Is there a spec for the database/header format? Then, I might be able to investigate this with my database. I couldn't find a spec when I was writing a small KeePass Python library a few years ago.

**Comment by J-Jamet** [comment]
@ladidadida Thank you for your test database, I will debug with it, it's perfect! 
@lgrahl  https://gist.github.com/lgg/e6ccc6e212d18dd2ecd8a8c116fb1e45 (or best to look in the original KeePass source code)
I will check this once I have completed the migration to AndroidX and integration of the new fingerprint API. Sorry for this issue anyway.

**Comment by J-Jamet** [comment]
@ladidadida  I can't replicate the issue with your database, it works very well with KeePass DX on my devices. (Even on my Galaxy S2 I9100 an Galaxy S I9000 with low memory, it only takes time)

**Comment by J-Jamet** [comment]
According to what's written @wheybags, I think the problem comes from one or more entries imported from an old database, there may be an unrecognized format or a TAG xml that is not not closed, or an object of history that is not good, hard to say.

**Comment by ladidadida** [comment]
> @ladidadida I can't replicate the issue with your database, it works very well with KeePass DX on my devices. (Even on my Galaxy S2 I9100 an Galaxy S I9000 with low memory, it only takes time)

Hi @J-Jamet, maybe my post was a little confusing. I wanted to state, that the database I uploaded is OK. I was NOT able to generate a DB that shows the same behaviour even though it already contained more entries than my real faulty DB.

**Comment by J-Jamet** [comment]
Hi @ladidadida I did not understand that, sorry.
If we can not reproduce the anomaly it is problematic. If the problem comes from a data formatting error that is dynamically fixed on desktop apps, it will be very hard to fix (especially if I can't debug :/).

**Comment by J-Jamet** [comment]
I think I solved the problem. The utility methods in `MemUtil` still used Java code. After converting the file to Kotlin, I could reproduce the OOM, so I improved the `copyStream` method that did not handle a buffer for the InputStream. I think some virtual machines automatically compensated the memory by an automatic buffer. You will tell me if it is resolved for you in the next version 2.5.0.0beta23 or if you compile the develop branch.

**Comment by J-Jamet** [comment]
Normally corrected, tell me if it's ok with version 2.5.0.0beta23

**Comment by leviwheatcroft** [comment]
I'm still having this issue with 2.5.0.0beta24

Reluctant to share the db it's occurring with.

The db is indeed generated / edited by KeePassXC, downloaded to android via nextcloud.

Anything I can do to help track this down ?

**Comment by lgrahl** [comment]
Sorry for radio silence. Also still an issue here and I can offer debugging.

**Comment by theScrabi** [comment]
By the way. I had this issue before. Turns out this happens when you have files saved in your database this happens. I removed some files than it worked again. Now when it happens again just remove some more files.

I suggest to not store files in keepass databases, but instead put them into an encrypted volume like veracrypt or crypted 7zip.

**Comment by J-Jamet** [comment]
Yes that's right, so I put `setConfirmationRequired(false)` to open a database, but I leave `setConfirmationRequired(true)` to store a credential.

**Comment by leviwheatcroft** [comment]
@theScrabi can you be sure that the files are actually the problem? I mean, when this occurs, it seems like any edit to the database in KeePassXC might resolve it. So removing a file might work just because it's an update, it doesn't necessarily mean that the file was the problem.

**Comment by theScrabi** [comment]
I could look for the original issue. for me it compleatly solved the issue. My database is now working since weeks again. If I would just change it without removing files it would just work until i change it again. Try it for your self.

**Comment by J-Jamet** [comment]
I'm working on this issue in my fork and I notified several structural problems:
- The parser is an XML pull and the nextText() method that retrieves data from the XML may not work properly if there is a large amount of data to retrieve.  (No real solution, maybe use a parser SAX but less fast and forced to redo all the parser.)
- The data is only exchanged with byte arrays, which uses a large amount of information for the transfer. (Better to use stream with buffer and store temp files in app storage)
- Zip files are only done on the fly by converting byte array. (Which can not be done with large volumes, solution is to use stream)
- Binary data is not stored in the same way for KDBX3.1 or KDBX4.0 files, which can cause bugs.(https://github.com/keepassxreboot/keepassxc-specs/blob/master/kdbx-xml/rfc.md)
- The Argon2 key derivation with a large RAM set in KeePass XC prevents proper opening. (solution is to lower the memory used and increase the iterations)

**Comment by J-Jamet** [comment]
I made a first code improvement pass but there is still work. I'm going to centralize these elements in a single new issue.

**Comment by J-Jamet** [comment]
I have improved the system for recognizing variables in C which are no longer cast without verification. I also updated BouncyCastle.
Those who had the Out Of Memory problem, can you tell me if it is resolved with version 2.5RC2?
In any case, I will try to improve the threads with coroutines.

**Comment by J-Jamet** [comment]
Since I don't have an answer, I think the problem is solved for you. So I close the issue. If someone encounters the problem again, please open a new issue and link the number.

**Comment by TheLonelyGhost** [comment]
FWIW, I haven't had OOM issues for the past few updates. LGTM!

**Comment by J-Jamet** [comment]
@TheLonelyGhost Very good! :+1:  (*when I saw the notification of your message, I thought there was a problem. :face_with_thermometer:*)

**Comment by XCSIV** [comment]
> @TheLonelyGhost Very good! 👍 (_when I saw the notification of your message, I thought there was a problem. 🤒_)

I am very sorry, but this or a similar problem still occurs. You can reproduce it as often as needed.

(Samsung Galaxy S21 Ultra, 256gb, latest Android and App Release)
- One single database entry with a large file is enough: e.g. pick a 200mb or 400mb video file. With compression turned on the app crashes while saving, with compression turned off it doesnt crash. The result is the same in both cases an out of memory exception when trying to reopen. Database file is stored locally and not touched by other processes. App is used in foreground the whole time.

**Comment by J-Jamet** [comment]
@1661410107114145152525 Is the video file you are using as a key file or as a file attached to an entry?

> With compression turned on the app crashes while saving, with compression turned off it doesn't crash.

So I take it that you have already managed to open it but not to save it?
I will try to reproduce the problem. But obviously, the database is not designed to host videos.

**Comment by 1661410107114145152525** [comment]
@J-Jamet Thanks for your fast answer! 

I do not need the file attachements but I used them to simulate huge databases with a lot of keys or saved text notes. If the current workaround would be to just not attach files its absolutely perfect for me - I have encrypted cloud drives for secure file saving.

BUT I am a bit scared of running into an OOM exception while the database is growing, do you have some kind of test file for this or an idea how to create one without using attachements? Or can you assure me, it is only an attachement related issue? 

Regarding your questions:

1) I am using the video as a file attached to an entry (.mp4 v2).
2) If compression is turned off the saving does not crash, but in both cases (compression on or off) I am unable to open the database again cause of the out of memory exception.

I tried out some further things to investigate the problem a bit in die UI:
a) using smaller files like 90 - 130mb and creating multiple entries with different titles and files: It works even with compression turned on UNTIL it reaches some sort of upper limit (3rd or 4th file it crashes)
b) the same error occurs in keepass2android too

I hope that helps, let me know if I can do something to help!

**Comment by 1661410107114145152525** [comment]
@J-Jamet Thank you very much for reopening working on it! Have you been able to reproduce the problem on your device?

**Comment by J-Jamet** [comment]
Yes
I had already made the feature (not easy at all by the way) that saves on the fly in encrypted files instead of RAM the attachments that are too big, and I think the problem is that the method that calculates the remaining RAM must not work all the time.
https://github.com/Kunzisoft/KeePassDX/blob/f1b56fed162ed33750fbc77e1e19a059105a2f36/app/src/main/java/com/kunzisoft/keepass/database/element/binary/BinaryData.kt#L184

So I'm going to debug it and add a condition that says : "if a file is over 5 or 10 MB, put it in an encrypted file instead of RAM anyway".

In any case, you won't have any problems with the current KeePassDX version if the attachments are small, here it's the outputstream that stalls when it can't allocate memory for a single large file.

**Comment by J-Jamet** [comment]
When I return `false` all the time in the `canMemoryBeAllocatedInRAM` method, I don't have any problem but the database takes a long time to open, which is normal since it is stored in a file so IO accesses are slower.

**Comment by 1661410107114145152525** [comment]
@J-Jamet Wow, thanks for the fast bugfixing and the provided details! I am very excited on that new version 🥳 when will the fix be available in playstore or F-Droid?

**Comment by J-Jamet** [comment]
Honestly I don't know, it's not a big bug since almost nobody will be in the case of a huge file, especially since there is the warning. And since I also have to set up the InputStream for the key file, I'll do it at the same time. The 3.3.0 version is not even validated by Google yet.

**Comment by 1661410107114145152525** [comment]
@J-Jamet Okey, thanks for your help! :) So while using attachements <= 5mb I am safe, even If the database file gets 5gb or sth. like that?

**Comment by J-Jamet** [comment]
It depends on the memory of your device, but to completely fill the RAM with 5MB attachments each, I don't know what you want to put in there, but it happens very very rarely, you really have to do it on purpose.
Because you should always keep in mind not to overload the database so that it can be opened more quickly.
I advise you to read this page of the wiki: https://github.com/Kunzisoft/KeePassDX/wiki/Attachments
The new version will arrive in any case.

_Note that all other KeePass clients don't even bother to check this kind of case, they put everything in RAM and that's it._
_Other note : You should always make backups_

**Comment by 1661410107114145152525** [comment]
Thanks for your answer and the wiki page. Currently I tried to do it on purpose with 4-5mb image files, spread to around 60 entries at the moment. Will it crash or throw OOM when I reach 100-200 entries, resulting in a 400-800mb database?

Is there a platform, where the releases are coming faster than on googles play store? (e.g. F-Droid)

**Comment by J-Jamet** [comment]
As I said, it depends on your device.

I'm not going to rush to release this version when the current behavior is the normal one and behaves like all other KeePass applications and programs. Here the bug is only in the advanced function of saving attachments in the physical memory of the application.

Of course you will have problems if you try to overload the database at all costs, if you use a glass or a thimble to fill a basin with all the water of a swimming pool, it will inevitably overflow.
It's like all programs, you can also have fun opening a text file in libre office and add content until the program crashes, it's fun to do but the interest is limited. The goal is to be careful and to put only the necessary information, as it is indicated in the wiki.

**Comment by 1661410107114145152525** [comment]
Sure, thank you very much! What database size would you consider as safe on almost any device?

**Comment by J-Jamet** [comment]
3.3.1 released
